# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree_q5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(661, 526)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 611, 61))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.a = QtWidgets.QLineEdit(Dialog)
        self.a.setGeometry(QtCore.QRect(440, 90, 113, 22))
        self.a.setObjectName("a")
        self.c = QtWidgets.QLineEdit(Dialog)
        self.c.setGeometry(QtCore.QRect(440, 120, 113, 22))
        self.c.setObjectName("c")
        self.b = QtWidgets.QLineEdit(Dialog)
        self.b.setGeometry(QtCore.QRect(440, 150, 113, 22))
        self.b.setObjectName("b")
        self.r = QtWidgets.QLineEdit(Dialog)
        self.r.setGeometry(QtCore.QRect(440, 180, 113, 22))
        self.r.setObjectName("r")
        self.r2 = QtWidgets.QLineEdit(Dialog)
        self.r2.setGeometry(QtCore.QRect(440, 350, 113, 22))
        self.r2.setObjectName("r2")
        self.b2 = QtWidgets.QLineEdit(Dialog)
        self.b2.setGeometry(QtCore.QRect(440, 320, 113, 22))
        self.b2.setObjectName("b2")
        self.a2 = QtWidgets.QLineEdit(Dialog)
        self.a2.setGeometry(QtCore.QRect(440, 260, 113, 22))
        self.a2.setObjectName("a2")
        self.c2 = QtWidgets.QLineEdit(Dialog)
        self.c2.setGeometry(QtCore.QRect(440, 290, 113, 22))
        self.c2.setObjectName("c2")
        self.s = QtWidgets.QLineEdit(Dialog)
        self.s.setGeometry(QtCore.QRect(200, 141, 113, 31))
        self.s.setObjectName("s")
        self.m = QtWidgets.QLineEdit(Dialog)
        self.m.setGeometry(QtCore.QRect(200, 191, 113, 31))
        self.m.setObjectName("m")
        self.n = QtWidgets.QLineEdit(Dialog)
        self.n.setGeometry(QtCore.QRect(200, 91, 113, 31))
        self.n.setObjectName("n")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 161, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 171, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(140, 200, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(410, 120, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(410, 150, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(410, 90, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(410, 290, 55, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(410, 320, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(410, 260, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(410, 180, 55, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(410, 350, 55, 16))
        self.label_12.setObjectName("label_12")
        self.m_available = QtWidgets.QCheckBox(Dialog)
        self.m_available.setGeometry(QtCore.QRect(200, 230, 111, 20))
        self.m_available.setObjectName("m_available")
        self.print = QtWidgets.QTextBrowser(Dialog)
        self.print.setGeometry(QtCore.QRect(30, 320, 291, 171))
        self.print.setObjectName("print")
        self.x_calc = QtWidgets.QPushButton(Dialog)
        self.x_calc.setGeometry(QtCore.QRect(420, 410, 131, 28))
        self.x_calc.setObjectName("x_calc")
        self.calc = QtWidgets.QPushButton(Dialog)
        self.calc.setGeometry(QtCore.QRect(420, 460, 131, 31))
        self.calc.setObjectName("calc")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">расчёт интервала справедливых цен в случае Европейского опциона</span></p><p align=\"center\"><span style=\" font-size:9pt;\">для триномиальной модели (B,S)-рынка с барьером</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Количество новых слоёв"))
        self.label_3.setText(_translate("Dialog", "Начальное значение акции"))
        self.label_4.setText(_translate("Dialog", "Барьер"))
        self.label_5.setText(_translate("Dialog", "c"))
        self.label_6.setText(_translate("Dialog", "b"))
        self.label_7.setText(_translate("Dialog", "a"))
        self.label_8.setText(_translate("Dialog", "c2"))
        self.label_9.setText(_translate("Dialog", "b2"))
        self.label_10.setText(_translate("Dialog", "a2"))
        self.label_11.setText(_translate("Dialog", "r"))
        self.label_12.setText(_translate("Dialog", "r2"))
        self.m_available.setText(_translate("Dialog", "С барьером"))
        self.x_calc.setText(_translate("Dialog", "Расчёт капитала"))
        self.calc.setText(_translate("Dialog", "Стоимость акции"))

